- name: Deploy SlackBot Raspbian
  hosts: localhost
  become: false
  user: pi

  tasks:
  - name: Install python library requirements
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    with_items:
      - { name: asn1crypto, version: 0.22.0 }
      - { name: beautifulsoup4, version: 4.6.0 }
      - { name: certifi, version: 2017.4.17 }
      - { name: cffi, version: 1.10.0 }
      - { name: chardet, version: 3.0.4 }
      - { name: configparser, version: 3.5.0 }
      - { name: contextlib2, version: 0.5.5 }
      - { name: coverage, version: 4.4.1 }
      - { name: cryptography, version: 1.9 }
      - { name: enum34, version: 1.1.6 }
      - { name: flake8, version: 3.3.0 }
      - { name: funcsigs, version: 1.0.2 }
      - { name: html5lib, version: 0.999999999 }
      - { name: idna, version: 2.5 }
      - { name: ipaddress, version: 1.0.18 }
      - { name: mccabe, version: 0.6.1 }
      - { name: mock, version: 2.0.0 }
      - { name: pbr, version: 3.1.0 }
      - { name: pluggy, version: 0.4.0 }
      - { name: py, version: 1.4.34 }
      - { name: pycodestyle, version: 2.3.1 }
      - { name: pycparser, version: 2.17 }
      - { name: pyfiglet, version: 0.7.5 }
      - { name: pyflakes, version: 1.5.0 }
      - { name: pyOpenSSL, version: 17.0.0 }
      - { name: pytest, version: 3.1.2 }
      - { name: pytest-cov, version: 2.5.1 }
      - { name: PyYAML, version: 3.12 }
      - { name: requests, version: 2.18.1 }
      - { name: six, version: 1.10.0 }
      - { name: tox, version: 2.7.0 }
      - { name: urllib3, version: 1.21.1 }
      - { name: vcrpy, version: 1.11.1 }
      - { name: virtualenv, version: 15.1.0 }
      - { name: webencodings, version: 0.5.1 }
      - { name: websocket-client, version: 0.44.0 }
      - { name: wrapt, version: 1.10.11 }
      - { name: python-jenkins, version: 0.4.15 }
